#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Code styling, testing and building your project before committing'

# Style local modified work
npm run stage-all

# Check ESLint Standards
npm run check:lint ||
(
  echo '😤🏀👋😤 YOU LINT LICKER - Get that weak sh*t out of here! 😤🏀👋😤
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
  false;
)

# echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# Check Build
# npm run build:dev ||
# (
#   echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#     Next build failed: View the errors above to see why.';
#   false;
# )
# && npm run unbuild

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
